services:
  - type: web
    name: browser-based-dss
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: DB_HOST
        value: myapp-db.chks4qwiiptd.ap-south-1.rds.amazonaws.com
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: ad_dss
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
